import { useState, useEffect } from 'react';
import { nanoid } from 'nanoid';
import copy from 'copy-to-clipboard';
import Head from 'next/head';
import Navbar from '../components/navbar';
import Uuid from '../components/uuid';
import CopyIcon from '../components/icon/copy';



export default function Home() {
  const [newNanoId, setNewNanoId] = useState('');
  
  const generateNewNanoId = () => setNewNanoId(nanoid());

  useEffect(() => {
    console.log("useEffect ");
    generateNewNanoId()
  },[])


  const copyId = (id) => copy(id);

  return (
    <div>
      <Uuid/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container  px-10 mx-auto">
        <Navbar />

        <section className="text-center px-8 py-20">
          <h2 className="text-[50px]">Get Online Nano Id</h2>
          <span className="text-xl">{newNanoId}</span>

          <button className="ml-10 btn btn-primary" onClick={() => generateNewNanoId()}>Button</button>


          <div className="tooltip tooltip-bottom" data-tip="Copy">
          <button className="btn btn-square btn-outline" onClick={() => copyId(newNanoId)}>
            <CopyIcon />
          </button>
          </div>

        </section>
      </main>
    </div>
  )
}
